FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y apt-utils

# Install common / shared packages
RUN apt-get install -y \
    curl \
    locales \
    software-properties-common \
    python-software-properties

# Set up locales
RUN locale-gen en_US.UTF-8
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8
RUN /usr/sbin/update-locale

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C \
    && apt-get update

# Per-image commands
ENV PHP_DIR /etc/php/{{ version }}
ENV PHP_FPM php{{ version }}-fpm
ARG SYSTEM_PACKAGES
ARG PHP_MODULES
WORKDIR $PHP_DIR

COPY ./version-specific-packages.sh version-specific-packages.sh

RUN chmod +x ${PHP_DIR}/version-specific-packages.sh \
    && add-apt-repository ppa:ondrej/php \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y ${PHP_FPM} ${SYSTEM_PACKAGES} \
    && if [ ! -z "$PHP_MODULES" ]; then \
        apt-get install --no-install-recommends --no-install-suggests -y $(${PHP_DIR}/version-specific-packages.sh "{{ version }}" "${PHP_MODULES}") \
    ;fi \
    && apt-get -y --purge autoremove \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ARG PEAR_MODULES
RUN if [ ! -z "$PEAR_MODULES" ]; then \
    printf "\n" | pear install -o -f ${PEAR_MODULES} \
;fi

ARG PECL_MODULES
RUN if [ ! -z "$PECL_MODULES" ]; then \
    pecl channel-update pecl.php.net \
    && printf "\n" | pecl install -o -f ${PECL_MODULES} \
;fi

ARG INSTALL_COMPOSER=false
RUN if [ $INSTALL_COMPOSER=1 ]; then \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
;fi

ARG INSTALL_BLACKFIRE=false
RUN if [ $INSTALL_COMPOSER=1 ]; then \
    version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp \
    && mv /tmp/blackfire-*.so $(php -r "echo ini_get('extension_dir');")/blackfire.so \
    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n" > ${PHP_DIR}/cli/conf.d/blackfire.ini \
    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n" > ${PHP_DIR}/fpm/conf.d/blackfire.ini \
;fi

EXPOSE 9000

CMD ["/usr/sbin/php-fpm{{ version }}", "--nodaemonize", "--force-stderr", "--allow-to-run-as-root"]
